# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StaffMen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'TransitionButton'
	pod 'IQKeyboardManagerSwift'
  	pod 'Alamofire'
    	pod 'AlamofireImage'
  	pod 'SwiftyJSON'
  	pod 'MaterialControls'
	pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git'
  	pod 'ImagePicker'
  	pod 'ReachabilitySwift'
  	pod 'Kingfisher'
  	pod 'MaterialControls'
	pod 'GooglePlaces'
  	pod 'GooglePlacePicker'
  	pod 'GoogleMaps'
	pod "MotionAnimation", :git => 'https://github.com/LondonAppWorks/MotionAnimation.git'
	pod 'SDWebImage'

  # Pods for StaffMen

end